/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package locadora.visao;

import java.util.List;
import javax.swing.JOptionPane;
import locadora.Database;
import locadora.Fabrica;
import locadora.controle.LocacaoControle;
import locadora.modelo.Cliente;
import locadora.modelo.Filme;
import locadora.modelo.Locacao;
import locadora.tabelas.TabelaLocacao;

public class LocacaoVisao extends javax.swing.JPanel {

    protected TabelaLocacao modeloTabela;
    private LocacaoControle controle;

    /**
     * Creates new form LocacaoVisao
     */
    public LocacaoVisao() {
        modeloTabela = new TabelaLocacao(Database.getInstance().getLocacoes());
        controle = (LocacaoControle) Fabrica.getFabrica("locacao").criaControle();
        initComponents();
        addDialog.pack();
        addDialog.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {//GEN-BEGIN:initComponents

        addDialog = new javax.swing.JDialog();
        clienteLabel = new javax.swing.JLabel();
        addConfirmButton = new javax.swing.JButton();
        addCancelButton = new javax.swing.JButton();
        clienteBox = new javax.swing.JComboBox<>();
        filmeBox = new javax.swing.JComboBox<>();
        filmeLabel = new javax.swing.JLabel();
        pane = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        addButton = new javax.swing.JButton();
        removeButton = new javax.swing.JButton();

        addDialog.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addDialog.setTitle("Nova Locação");
        addDialog.setAlwaysOnTop(true);
        addDialog.setResizable(false);

        clienteLabel.setText("Cliente:");

        addConfirmButton.setText("Confirmar");
        addConfirmButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addConfirmButtonActionPerformed(evt);
            }
        });

        addCancelButton.setText("Cancelar");
        addCancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCancelButtonActionPerformed(evt);
            }
        });

        filmeLabel.setText("Filme:");

        javax.swing.GroupLayout addDialogLayout = new javax.swing.GroupLayout(addDialog.getContentPane());
        addDialog.getContentPane().setLayout(addDialogLayout);
        addDialogLayout.setHorizontalGroup(
            addDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(addDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addDialogLayout.createSequentialGroup()
                        .addGroup(addDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(clienteLabel)
                            .addComponent(filmeLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(addDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(filmeBox, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(clienteBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addDialogLayout.createSequentialGroup()
                        .addGap(0, 138, Short.MAX_VALUE)
                        .addComponent(addConfirmButton)
                        .addGap(38, 38, 38)
                        .addComponent(addCancelButton)))
                .addContainerGap())
        );
        addDialogLayout.setVerticalGroup(
            addDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(addDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clienteLabel)
                    .addComponent(clienteBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(filmeBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(filmeLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addConfirmButton)
                    .addComponent(addCancelButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        table.setAutoCreateRowSorter(true);
        table.setModel(modeloTabela);
        pane.setViewportView(table);

        addButton.setText("Adicionar");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        removeButton.setText("Remover");
        removeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pane, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(addButton, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                        .addGap(129, 129, 129)
                        .addComponent(removeButton, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pane, javax.swing.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addButton)
                    .addComponent(removeButton))
                .addContainerGap())
        );
    }//GEN-END:initComponents

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        setEnabled(false);
        carregarClienteBox(Database.getInstance().getClientes());
        carregarFilmeBox(Database.getInstance().getFilmes());
        addDialog.setVisible(true);
    }//GEN-LAST:event_addButtonActionPerformed

    private void removeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeButtonActionPerformed
        try {
            controle.removerLocacao(modeloTabela.getValueAt(table.convertRowIndexToModel(table.getSelectedRow())));
        } catch (IndexOutOfBoundsException e) {
            JOptionPane.showMessageDialog(this, "Selecione um filme", "Não é possível remover",
                    JOptionPane.ERROR_MESSAGE);
        }
        modeloTabela.fireTableDataChanged();
    }//GEN-LAST:event_removeButtonActionPerformed

    private void addConfirmButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addConfirmButtonActionPerformed
        Cliente cliente = Database.getInstance().getClientes().get(clienteBox.getSelectedIndex());

        for(Filme filme : Database.getInstance().getFilmes()){
            if(filme.getNome().equals(filmeBox.getSelectedItem())){
                controle.adicionarLocacao(cliente, filme);
                break;
            }
        }
        modeloTabela.fireTableDataChanged();
        
        addDialog.dispose();
        setEnabled(true);
    }//GEN-LAST:event_addConfirmButtonActionPerformed

    private void addCancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCancelButtonActionPerformed
        addDialog.dispose();
        setEnabled(false);
    }//GEN-LAST:event_addCancelButtonActionPerformed

    public void update() {
        modeloTabela.fireTableDataChanged();
    }

    public void update(List<Locacao> locacoes) {
        modeloTabela.setLocacoes(locacoes);
        modeloTabela.fireTableDataChanged();
    }

    public void carregarClienteBox(List<Cliente> clientes){
        clienteBox.removeAllItems();
        for(Cliente cliente : clientes) {
            clienteBox.addItem(cliente.getNome());
        }
    }

    public void carregarFilmeBox(List<Filme> filmes){
        filmeBox.removeAllItems();
        for(Filme filme : filmes){
            if(!filme.isAlugado()){
                filmeBox.addItem(filme.getNome());
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JButton addCancelButton;
    private javax.swing.JButton addConfirmButton;
    private javax.swing.JDialog addDialog;
    private javax.swing.JComboBox<String> clienteBox;
    private javax.swing.JLabel clienteLabel;
    private javax.swing.JComboBox<String> filmeBox;
    private javax.swing.JLabel filmeLabel;
    private javax.swing.JScrollPane pane;
    private javax.swing.JButton removeButton;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}